name: 'Deploy UI to Cloudflare Pages'
description: 'Deploy or delete a Cloudflare Pages deployment'
branding:
  icon: 'cloud'
  color: 'orange'
inputs:
  CLOUDFLARE_API_TOKEN:
    description: 'Cloudflare API token with Pages permissions'
    required: true
  CLOUDFLARE_ACCOUNT_ID:
    description: 'Cloudflare account ID'
    required: true
  DIST_FOLDER:
    description: 'Path to the distribution folder that will be deployed'
    required: true
  PROJECT_NAME:
    description: 'Cloudflare Pages project name'
    required: true
  BRANCH:
    description: 'Git branch to deploy to (defaults to "main")'
    required: false
    default: 'main'
  EVENT:
    description: 'Action to perform: deploy or delete'
    required: false
    default: 'deploy'
  HEADERS:
    description: 'JSON string of custom headers configuration (e.g. {"version.json":{"cacheControl":"max-age=0,no-cache,no-store,must-revalidate"}})'
    required: false
    default: '{}'
  GITHUB_TOKEN:
    description: 'GitHub token for creating deployment statuses on PR'
    required: false
  ENVIRONMENT_NAME:
    description: 'Name of the environment for GitHub deployment (e.g. "preview" or "production")'
    required: false
    default: 'preview'
outputs:
  url:
    description: 'URL of the deployed site (only available when EVENT is "deploy")'
runs:
  using: 'node16'
  main: 'dist/index.js'